language: node_js

node_js:
  - 10
  - 12

cache: yarn

before_install:
  - travis_retry yarn global add aegir@17 truffle@4 ganache-cli@6

install:
  - travis_retry yarn install

before_script:
  # Start Ganache CLI
  - ganache-cli | head -42 &

  # Deploy smart contract to Ganache CLI
  - |
    (
      git clone https://github.com/gitcoinco/ethavatar.git /tmp/ethavatar
      cd /tmp/ethavatar
      printf "module.exports = {\nnetworks: {\ndevelopment: {\nhost: \"127.0.0.1\",\nport: 8545,\nnetwork_id: \"*\"\n}\n}\n}" > truffle.js
      rm -rf build && truffle migrate
    )

  # Copy smart contract to package
  - cp /tmp/ethavatar/build/contracts/EthAvatar.json $TRAVIS_BUILD_DIR/src/data/EthAvatar.json

script:
  # Run lint and test
  - yarn lint
  - yarn test:node

  # Display coverage
  - yarn coverage 2> /dev/null | sed -n -e '/----------/,$p' | sed \$d

before_deploy:
  # Remove smart contract changes
  - git checkout -- $TRAVIS_BUILD_DIR/src/data/EthAvatar.json

  # Set latest tag as version
  - npm version -no-git-tag-version $(git describe --abbrev=0 --tags)

  # Make documentation and build code
  - yarn docs
  - yarn build

  # Use custom subdomain for docs
  - echo 'ethavatar.js.org' > ./docs/CNAME

deploy:
  - provider: pages
    skip_cleanup: true
    on:
      branch: master
      node: 12
    github_token: $GH_TOKEN
    local_dir: docs

  - provider: npm
    skip_cleanup: true
    on:
      tags: true
      node: 12
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
