language: node_js

node_js:
  - 8
  - 10
  - 11

cache: yarn

before_install:
  - travis_retry yarn global add aegir truffle ganache-cli

install:
  - travis_retry yarn install

before_script:
  # Start Ganache CLI
  - ganache-cli | head -42 &

  # Deploy smart contract to Ganache CLI
  - |
    (
      git clone https://github.com/gitcoinco/ethavatar.git /tmp/ethavatar
      cd /tmp/ethavatar
      printf "module.exports = {\nnetworks: {\ndevelopment: {\nhost: \"127.0.0.1\",\nport: 8545,\nnetwork_id: \"*\"\n}\n}\n}" > truffle.js
      rm -rf build && truffle migrate
    )

  # Copy smart contract to package
  - cp /tmp/ethavatar/build/contracts/EthAvatar.json $TRAVIS_BUILD_DIR/src/data/EthAvatar.json

script:
  # Run lint and test
  - yarn lint
  - yarn test:node

  # Display coverage
  - yarn coverage 2> /dev/null | sed -n -e '/----------/,$p' | sed \$d

after_success:
  # Set Git user and branch
  - git config --global user.email "travis@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git checkout -qf master

  # Update smart contract
  - wget https://raw.githubusercontent.com/gitcoinco/ethavatar/master/build/contracts/EthAvatar.json -O src/data/EthAvatar.json
  - git add src/data/EthAvatar.json
  - git commit -m "[ci skip] Update smart contract"

  # Build documentation
  - yarn docs
  - git add docs
  - git commit -m "[ci skip] Build documentation"

  # Publish to GitHub
  - |
    if [[ ${TRAVIS_NODE_VERSION:0:2} == "10" ]]
    then
      git push --set-upstream https://${GH_TOKEN}@github.com/filips123/EthAvatar.JS.git master > /dev/null 2>&1 && echo Code published successfully || echo Error while publishing code
    fi

deploy:
  provider: script
  skip_cleanup: true
  on:
    tags: true
  script:
    - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > $HOME/.npmrc
    - yarn build
    - yarn publish --non-interactive
